return {}

-- return {
-- 	"akinsho/bufferline.nvim",
-- 	version = "*",
-- 	dependencies = {
-- 		"nvim-tree/nvim-web-devicons",
-- 	},
-- 	event = "VimEnter",
-- 	opts = {
-- 		options = {
-- 			mode = "buffers",
-- 			themable = true,
-- 			numbers = "ordinal",
-- 			close_command = "bdelete! %d",
-- 			right_mouse_command = "bdelete! %d",
-- 			left_mouse_command = "buffer %d",
-- 			indicator = { icon = "▎", style = "icon" },
-- 			buffer_close_icon = "×",
-- 			modified_icon = "●",
-- 			close_icon = "",
-- 			left_trunc_marker = "",
-- 			right_trunc_marker = "",
-- 			max_name_length = 30,
-- 			max_prefix_length = 15,
-- 			truncate_names = true,
-- 			tab_size = 21,
-- 			diagnostics = "nvim_lsp",
-- 			diagnostics_update_in_insert = false,
-- 			diagnostics_indicator = function(count, level)
-- 				local icon = (level == "error" and "" or "")
-- 				return " " .. icon .. count
-- 			end,
-- 			offsets = {
-- 				{
-- 					filetype = "NvimTree",
-- 					text = "File Explorer",
-- 					text_align = "left",
-- 					separator = true,
-- 				},
-- 			},
-- 			color_icons = true,
-- 			show_buffer_icons = true,
-- 			show_buffer_close_icons = false,
-- 			show_close_icon = false,
-- 			show_tab_indicators = true,
-- 			show_duplicate_prefix = true,
-- 			persist_buffer_sort = true,
-- 			separator_style = "slant",
-- 			enforce_regular_tabs = false,
-- 			always_show_bufferline = true,
-- 			hover = { enabled = true, delay = 200, reveal = { "close" } },
-- 			sort_by = function(a, b)
-- 				return a.id < b.id
-- 			end,
-- 		},
-- 	},
-- 	config = function(_, opts)
-- 		require("bufferline").setup(opts)
-- 		local map = vim.keymap.set
-- 		for i = 1, 9 do
-- 			map("n", "<A-" .. i .. ">", function()
-- 				require("bufferline").go_to(i, true)
-- 			end, { silent = true, desc = "Go to buffer " .. i })
-- 		end
-- 		map("n", "<A-0>", function()
-- 			require("bufferline").go_to(-1, true)
-- 		end, { silent = true, desc = "Go to last buffer" })
-- 		map("n", "<A-,>", "<Cmd>BufferLineCyclePrev<CR>", { silent = true, desc = "Previous buffer" })
-- 		map("n", "<A-.>", "<Cmd>BufferLineCycleNext<CR>", { silent = true, desc = "Next buffer" })
-- 		map("n", "<A-<>", "<Cmd>BufferLineMovePrev<CR>", { silent = true, desc = "Move buffer left" })
-- 		map("n", "<A->>", "<Cmd>BufferLineMoveNext<CR>", { silent = true, desc = "Move buffer right" })
-- 		map("n", "<A-c>", "<Cmd>bdelete<CR>", { silent = true, desc = "Close buffer" })
-- 		map("n", "<leader>bc", "<Cmd>bdelete<CR>", { silent = true, desc = "Close buffer" })
-- 		map("n", "<leader>bC", "<Cmd>BufferLineCloseOthers<CR>", { silent = true, desc = "Close other buffers" })
-- 		map("n", "<leader>fb", function()
-- 			require("telescope.builtin").buffers({
-- 				sort_mru = true,
-- 				sort_lastused = true,
-- 				initial_mode = "normal",
-- 			})
-- 		end, { silent = true, desc = "Find buffers" })
-- 		map("n", "<C-h>", function()
-- 			local curr_win = vim.fn.winnr()
-- 			vim.cmd("wincmd h")
-- 			if curr_win == vim.fn.winnr() then
-- 				vim.cmd("BufferLineCyclePrev")
-- 				vim.cmd("redrawtabline")
-- 			end
-- 		end, { silent = true, desc = "Left window or prev buffer" })
-- 		map("n", "<C-l>", function()
-- 			local curr_win = vim.fn.winnr()
-- 			vim.cmd("wincmd l")
-- 			if curr_win == vim.fn.winnr() then
-- 				vim.cmd("BufferLineCycleNext")
-- 				vim.cmd("redrawtabline")
-- 			end
-- 		end, { silent = true, desc = "Right window or next buffer" })
-- 	end,
-- }
